# Generated by Django 3.2.8 on 2021-10-10 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game_app', '0002_heroeslist_itemlist_ongameusers_recordslist_shoplist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroeslist',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
