# Generated by Django 3.2.8 on 2021-10-19 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game_app', '0003_alter_heroeslist_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='ongameusers',
            name='status',
            field=models.CharField(default='play', max_length=200),
        ),
        migrations.AlterField(
            model_name='recordslist',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shoplist',
            name='item_cost',
            field=models.IntegerField(),
        ),
    ]
