# Generated by Django 3.2.8 on 2021-10-21 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0006_alter_shoplist_item_mame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoplist',
            name='item_cost',
        ),
        migrations.RemoveField(
            model_name='shoplist',
            name='item_mame',
        ),
        migrations.RemoveField(
            model_name='shoplist',
            name='item_pic',
        ),
        migrations.AddField(
            model_name='itemlist',
            name='item_stats',
            field=models.JSONField(default=''),
        ),
        migrations.AddField(
            model_name='shoplist',
            name='item',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='game_app.itemlist'),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
