# Generated by Django 3.2.8 on 2021-10-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0007_auto_20211021_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroeslist',
            name='hero_inventory',
            field=models.JSONField(default=''),
        ),
        migrations.AddField(
            model_name='heroeslist',
            name='hero_lvl',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='heroeslist',
            name='hero_stats',
            field=models.JSONField(default=''),
        ),
    ]
