# Generated by Django 3.2.8 on 2021-10-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0011_rename_is_her0_profile_is_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroeslist',
            name='hero_pic',
            field=models.CharField(default='', max_length=200),
        ),
    ]
